// Generated by CoffeeScript 1.8.0
"use strict";
var addPoints, id, interpolateHsl, interval, lat, lng, map, mapOptions, mapStyle, n, running, step, styleFeature, xdir, xstep, ydir, ystep;

map = void 0;

mapStyle = [
  {
    'featureType': 'all',
    'elementType': 'all',
    'stylers': [
      {
        'invert_lightness': true
      }, {
        'saturation': -100
      }, {
        'lightness:': 15
      }
    ]
  }
];

mapOptions = {
  center: {
    lat: 59.346659,
    lng: 18.072063
  },
  zoom: 16,
  styles: mapStyle,
  disableDefaultUI: true,
  mapMaker: true,
  minZoom: 10
};

lat = 59.347282;

lng = 18.070712;

id = 1;

running = true;

step = 1;

n = 10;

xstep = 0;

ystep = 0;

xdir = 1;

ydir = 1;

interval = 500;

styleFeature = function(feature) {
  var color, fraction, high, low, max, min;
  low = [134, 91, 50];
  high = [0, 100, 50];
  min = 1.0;
  max = 12.0;
  fraction = (Math.min(feature.getProperty('velocity'), max) - min) / (max - min);
  color = interpolateHsl(low, high, fraction);
  return {
    icon: {
      path: google.maps.SymbolPath.CIRCLE,
      strokeWeight: 2,
      strokeColor: "#eee",
      fillColor: color,
      fillOpacity: 1,
      scale: 12
    },
    zIndex: Math.floor(feature.getProperty('id'))
  };
};

interpolateHsl = function(lowHsl, highHsl, fraction) {
  var color, i;
  color = [];
  i = 0;
  while (i < 3) {
    color[i] = (highHsl[i] - lowHsl[i]) * fraction + lowHsl[i];
    i++;
  }
  return "hsl(" + color[0] + ", " + color[1] + "%, " + color[2] + "%)";
};

addPoints = function() {
  var json, v;
  if (!running) {
    return;
  }
  v = Math.random() * 11 + 1;
  xstep = Math.random() / 1000;
  ystep = Math.random() / 1000;
  if (step % n === 0) {
    xdir = Math.random() * 2 - 1;
    ydir = Math.random() * 2 - 1;
    n = Math.floor(Math.random() * 15 + 1);
  }
  lat += xstep * xdir;
  lng += ystep * ydir;
  id++;
  step++;
  json = "{\n  \"type\": \"FeatureCollection\",\n  \"metadata\": {},\n  \"features\": [\n    {\n      \"type\": \"Feature\", \"properties\": {\"velocity\": " + v + "},\n      \"geometry\": {\n        \"type\": \"Point\",\n        \"coordinates\": [" + lng + ", " + lat + "]\n      },\n      \"id\": " + id + "\n    }\n  ],\n  \"bbox\": [-179.463, -60.7674, -2.9, 178.4321, 67.0311, 609.13]\n}";
  map.data.addGeoJson($.parseJSON(json));
  map.panTo({
    lat: lat,
    lng: lng
  });
};

google.maps.event.addDomListener(window, 'load', function() {
  map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
  map.data.setStyle(styleFeature);
});

$('*').keypress(function() {
  running = !running;
});

$(setInterval(addPoints, interval));


//# sourceMappingURL=points.js.map
